= Abstract


== 🛠️ Tech Stack - 技术栈


=== Languages - 编程语言

[.text-center]
--
image:https://img.shields.io/badge/Go-00ADD8?style=for-the-badge&logo=go&logoColor=white[Go, link="https://go.dev/", window="_blank"]
image:https://img.shields.io/badge/Rust-000000?style=for-the-badge&logo=rust&logoColor=white[Rust, link="https://rust-lang.org/", window="_blank"]
image:https://img.shields.io/badge/Zig-F7A41D?style=for-the-badge&logo=zig&logoColor=white[Zig, link="https://ziglang.org/", window="_blank"]
image:https://img.shields.io/badge/Red-FF0000?style=for-the-badge[Red, link="https://www.red-lang.org/", window="_blank"]
--

[.text-center]
--
image:https://img.shields.io/badge/C%2FC%2B%2B-00599C?style=for-the-badge&logo=c%2B%2B&logoColor=white[C/C++]
image:https://img.shields.io/badge/Java-ED8B00?style=for-the-badge&logo=openjdk&logoColor=white[Java]
image:https://img.shields.io/badge/C%23-239120?style=for-the-badge&logo=c-sharp&logoColor=white[C#]
image:https://img.shields.io/badge/PHP-777BB4?style=for-the-badge&logo=php&logoColor=white[PHP]
image:https://img.shields.io/badge/Python-3776AB?style=for-the-badge&logo=python&logoColor=white[Python]
image:https://img.shields.io/badge/TypeScript-007ACC?style=for-the-badge&logo=typescript&logoColor=white[TypeScript]
image:https://img.shields.io/badge/JavaScript-F7DF1E?style=for-the-badge&logo=javascript&logoColor=black[JavaScript]
--


=== Databases - 数据库

[.text-center]
--
image:https://img.shields.io/badge/Redis-DC382D?style=for-the-badge&logo=redis&logoColor=white[Redis]
image:https://img.shields.io/badge/MySQL-4479A1?style=for-the-badge&logo=mysql&logoColor=white[MySQL]
image:https://img.shields.io/badge/MongoDB-4EA94B?style=for-the-badge&logo=mongodb&logoColor=white[MongoDB]
image:https://img.shields.io/badge/PostgreSQL-336791?style=for-the-badge&logo=postgresql&logoColor=white[PostgreSQL]
--


=== OS & Platforms - 操作系统与平台

[.text-center]
--
image:https://img.shields.io/badge/macOS-000000?style=for-the-badge&logo=apple&logoColor=white[macOS]
image:https://img.shields.io/badge/Linux-FCC624?style=for-the-badge&logo=linux&logoColor=black[Linux]
image:https://img.shields.io/badge/Android-3DDC84?style=for-the-badge&logo=android&logoColor=white[Android]
--


=== Cloud Services - 云服务

[.text-center]
--
image:https://img.shields.io/badge/Google_Cloud-4285F4?style=for-the-badge&logo=google-cloud&logoColor=white[Google Cloud]
image:https://img.shields.io/badge/Amazon_AWS-232F3E?style=for-the-badge&logo=amazon-aws&logoColor=white[Amazon AWS]
--


=== Game Engines - 游戏引擎

[.text-center]
--
image:https://img.shields.io/badge/Bevy-FFFFFF?style=for-the-badge&logo=rust&logoColor=black[Bevy, link="https://github.com/bevyengine/bevy", window="_blank"]
image:https://img.shields.io/badge/Mach-F7A41D?style=for-the-badge&logo=zig&logoColor=white[Mach, link="https://github.com/hexops/mach", window="_blank"]
image:https://img.shields.io/badge/Godot-478CBF?style=for-the-badge&logo=godot-engine&logoColor=white[Godot, link="https://github.com/godotengine/godot", window="_blank"]
--

[.text-center]
--
image:https://img.shields.io/badge/Unreal_Engine-313131?style=for-the-badge&logo=unrealengine&logoColor=white[Unreal Engine]
image:https://img.shields.io/badge/Unity-100000?style=for-the-badge&logo=unity&logoColor=white[Unity]
image:https://img.shields.io/badge/Cocos-0DB2D4?style=for-the-badge&logo=cocos&logoColor=white[Cocos]
--


=== Graphics & Physics - 图形与物理

[.text-center]
--
image:https://img.shields.io/badge/Raylib-000000?style=for-the-badge[Raylib]
image:https://img.shields.io/badge/Box2D-3498DB?style=for-the-badge[Box2D]
image:https://img.shields.io/badge/OpenGL-5586A4?style=for-the-badge&logo=opengl&logoColor=white[OpenGL]
image:https://img.shields.io/badge/Shader-8A2BE2?style=for-the-badge[Shader]
--


=== GUI

[.text-center]
--
image:https://img.shields.io/badge/Gio_UI-00ADD8?style=for-the-badge&logo=go&logoColor=white[Gio UI, link="https://gioui.org/", window="_blank"]
--


=== Docs & Diagrams - 文档 & 图表

[.text-center]
--
image:https://img.shields.io/badge/AsciiDoc-E40046?style=for-the-badge&logo=asciidoctor&logoColor=white[AsciiDoc, link="https://asciidoc.org/", window="_blank"]
image:https://img.shields.io/badge/PlantUML-0B863F?style=for-the-badge[PlantUML, link="https://plantuml.com/", window="_blank"]
--

[.text-center]
--
image:https://img.shields.io/badge/Markdown-000000?style=for-the-badge&logo=markdown&logoColor=white[Markdown]
image:https://img.shields.io/badge/Mermaid-FF3670?style=for-the-badge&logo=mermaid&logoColor=white[Mermaid]
--


=== SSG (Static Site Generator) - 静态网站生成

[.text-center]
--
image:https://img.shields.io/badge/Astro-FF5D01?style=for-the-badge&logo=astro&logoColor=white[Astro, link="https://github.com/withastro/astro", window="_blank"]
image:https://img.shields.io/badge/Hugo-FF4088?style=for-the-badge&logo=hugo&logoColor=white[Hugo, link="https://github.com/gohugoio/hugo", window="_blank"]
--


=== Terminals - 终端

[.text-center]
--
image:https://img.shields.io/badge/Ghostty-2E2E2E?style=for-the-badge[Ghostty, link="https://github.com/ghostty-org/ghostty", window="_blank"]
--


=== Shells

[.text-center]
--
image:https://img.shields.io/badge/Nushell-4E9A06?style=for-the-badge[Nushell]
image:https://img.shields.io/badge/zsh-2B2724?style=for-the-badge[zsh]
image:https://img.shields.io/badge/Bash-4EAA25?style=for-the-badge&logo=gnu-bash&logoColor=white[Bash]
--


=== Editors & IDEs - 编辑器 与 IDEs

[.text-center]
--
image:https://img.shields.io/badge/JetBrains-000000?style=for-the-badge&logo=jetbrains&logoColor=white[JetBrains]
image:https://img.shields.io/badge/Google_Antigravity-4285F4?style=for-the-badge&logo=google&logoColor=white[Google Antigravity]
image:https://img.shields.io/badge/VS_Code-007ACC?style=for-the-badge&logo=visualstudiocode&logoColor=white[VS Code]
--

[.text-center]
--
image:https://img.shields.io/badge/Neovim-57A143?style=for-the-badge&logo=neovim&logoColor=white[Neovim, link="https://github.com/neovim/neovim", window="_blank"]
image:https://img.shields.io/badge/Helix-0F111A?style=for-the-badge[Helix, link="https://github.com/helix-editor/helix", window="_blank"]
image:https://img.shields.io/badge/micro-000000?style=for-the-badge[micro, link="https://github.com/micro-editor/micro", window="_blank"]
image:https://img.shields.io/badge/nano-18181A?style=for-the-badge[nano]
--

[.text-center]
--
image:https://img.shields.io/badge/Zed-10B981?style=for-the-badge[Zed, link="https://github.com/zed-industries/zed", window="_blank"]
image:https://img.shields.io/badge/Sublime_Text-FF9800?style=for-the-badge&logo=sublimetext&logoColor=white[Sublime Text]
--


=== DevTools & Misc - 杂项开发工具

[.text-center]
--
image:https://img.shields.io/badge/just-000000?style=for-the-badge[just, link="https://github.com/casey/just", window="_blank"]
--

[.text-center]
--
image:https://img.shields.io/badge/etcd-22699C?style=for-the-badge[etcd]
image:https://img.shields.io/badge/Protobuf-245980?style=for-the-badge[Protobuf]
image:https://img.shields.io/badge/Nginx-009639?style=for-the-badge&logo=nginx&logoColor=white[Nginx]
image:https://img.shields.io/badge/Caddy-00ADD8?style=for-the-badge[Caddy]
image:https://img.shields.io/badge/Docker-2496ED?style=for-the-badge&logo=docker&logoColor=white[Docker]
--

[.text-center]
--
image:https://img.shields.io/badge/Jenkins-D24939?style=for-the-badge&logo=jenkins&logoColor=white[Jenkins]
image:https://img.shields.io/badge/Ansible-EE0000?style=for-the-badge&logo=ansible&logoColor=white[Ansible]
--


== 🎵 Music - 音乐

[.text-center]
--
image:https://img.shields.io/badge/Logic_Pro-000000?style=for-the-badge&logo=logicpro&logoColor=white[Logic Pro]
image:https://img.shields.io/badge/lilypond-01796F?style=for-the-badge[lilypond, link="https://github.com/lilypond/lilypond", window="_blank"]
image:https://img.shields.io/badge/MuseScore-2453FF?style=for-the-badge&logo=musescore&logoColor=white[MuseScore, link="https://github.com/musescore/MuseScore", window="_blank"]
--

