name: SPS Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
  repository_dispatch:
    types:
      - sps_digital_garden_updated
      - astro_theme_linky_tree_updated

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    env:
      THEME: "linky-tree"
      SPS_DG_PATH: "./sps-digital-garden"
      SPS_SPSZERONE_GITHUB_IO_PATH: "./spszerone.github.io"

    steps:
      - name: Prepare Dynamic Environment Variables
        run: |
          echo "BUILD_PATH=./astro-theme-${{ env.THEME }}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ${{ env.SPS_SPSZERONE_GITHUB_IO_PATH }}
          ref: 'main'

      - name: Checkout astro-theme-linky-tree
        uses: actions/checkout@v4
        with:
          repository: SPSZerone/astro-theme-linky-tree
          ref: publish
          path: ${{ env.BUILD_PATH }}
          # token: ${{ secrets.SPS_DG_DOWNSTREAM_PUBLISH_PAT }}

      - name: Checkout sps-digital-garden
        uses: actions/checkout@v4
        with:
          repository: SPSZerone/sps-digital-garden
          ref: main
          path: ${{ env.SPS_DG_PATH }}
          token: ${{ secrets.SPS_DG_PUBLISH_PAT }}

      - name: Setup Nushell
        uses: hustcer/setup-nu@v3
        with:
          nu-version: '0.112.2'

      - name: "SPS Digital Garden -> scripts/publish.nu"
        run: nu ${{ env.SPS_DG_PATH }}/scripts/publish.nu -s astro -t ${{ env.THEME }} -p ${{ env.BUILD_PATH }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"
          cache-dependency-path: ${{ env.BUILD_PATH }}/pnpm-lock.yaml

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: ${{ env.BUILD_PATH }}

      - name: Build with Astro
        run: |
          pnpm run build \
            --site "${{ steps.pages.outputs.origin }}" \
            --base "${{ steps.pages.outputs.base_path }}"
        working-directory: ${{ env.BUILD_PATH }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.BUILD_PATH }}/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
