name: Build and Deploy (Triggered by astro-theme-linky-tree)

on:
  repository_dispatch:
    types: [update-from-astro-theme-linky-tree]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  BUILD_PATH: "./astro-theme-linky-tree"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo astro-theme-linky-tree (Source Code)
        uses: actions/checkout@v4
        with:
          repository: SPSZerone/astro-theme-linky-tree
          path: ${{ env.BUILD_PATH }}
          # token: ${{ secrets.REPO_PAT }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"
          cache-dependency-path: ${{ env.BUILD_PATH }}/pnpm-lock.yaml

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: ${{ env.BUILD_PATH }}

      - name: Build with Astro
        run: |
          pnpm run build \
            --site "${{ steps.pages.outputs.origin }}" \
            --base "${{ steps.pages.outputs.base_path }}"
        working-directory: ${{ env.BUILD_PATH }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.BUILD_PATH }}/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
